=== MikeKutz/templates/CTAN.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Michael Kutz (personal development) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="CTAN">
		<xs:annotation>
			<xs:documentation>A complete index list for CTAN</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="manifest" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="manifest">
		<xs:annotation>
			<xs:documentation>describes a single entry for CTAN</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="versions"/>
				<xs:element ref="tags" minOccurs="0"/>
				<xs:element name="requirements" type="xs:anyType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="guid" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="path" type="xs:anyURI"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="versions">
		<xs:annotation>
			<xs:documentation>A collection of individual versions for an entry.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="version" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="version">
		<xs:annotation>
			<xs:documentation>A version of the group of files</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="file" maxOccurs="unbounded"/>
				<xs:element ref="requirements" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="engine" type="xs:string" use="required"/>
			<xs:attribute name="major" type="xs:integer" use="required"/>
			<xs:attribute name="minor" type="xs:integer" use="required"/>
			<xs:attribute name="sub" type="xs:integer" use="required"/>
			<xs:attribute name="patch" type="xs:string" use="optional"/>
			<xs:attribute name="rdbms" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="file">
		<xs:annotation>
			<xs:documentation>A specific file that belongs to this version</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:anyURI">
					<xs:attribute name="type" type="xs:string" use="required"/>
					<xs:attribute name="process_order" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tags">
		<xs:annotation>
			<xs:documentation>List of tags useful for searching</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tag" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tag" type="xs:string">
		<xs:annotation>
			<xs:documentation>A simple word or phrase that is tagged to the entry.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="requirements">
		<xs:annotation>
			<xs:documentation>list of requirements. This is not yet fully designed.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="requirement" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MikeKutz/templates/DD/experimental/MANIFEST.xml
<?xml version="1.0" encoding="UTF-8" ?>
<manifest guid="{ 47CB-D263-67DB-4FC9-8CDE-A596-A604-57E0 }" class="DD" name="dd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../CTAN.xsd">
  <versions>
    <version engine="tePLSQL" major="0" minor="1" sub="0">
      <file type="readme" process_order="0">./README.md</file>
      <file type="sql" process_order="1">./TEPLSQL_DD_GENERATOR.pls</file>
      <file type="sql" process_order="2">./TEPLSQL_DD_GENERATOR.plb</file>
    </version>
  </versions>
  <tags>
    <tag>DD</tag>
    <tag>Data Dictionary</tag>
    <tag>oracle</tag>
    <tag>tePLSQL</tag>
  </tags>
  <requirements/>
</manifest>
